# Generated by Django 3.2.6 on 2021-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='articles',
        ),
    ]
