# Generated by Django 3.2.6 on 2021-09-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_articles_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
